### ISSUE TITLE
浏览器访问7000端口，控制台报错

### ISSUE THREAD

**Issue by zcjlq** [Ebookcoin/ebookcoin#10]
您好，根据您的教程安装ebookcoin，浏览器访问7000端口报错，报错文件为vendor_app.js，
[vendor_app.js.zip](https://github.com/Ebookcoin/ebookcoin/files/1241129/vendor_app.js.zip)

终端显示：
<img width="542" alt="2017-08-22 15 24 18" src="https://user-images.githubusercontent.com/25979570/29553584-598da438-874e-11e7-8bcb-35588d738346.png">
<img width="734" alt="2017-08-22 15 24 38" src="https://user-images.githubusercontent.com/25979570/29553586-5ad24538-874e-11e7-9a98-0966380ba550.png">

系统环境：Mac os Sierra 10.12.6
                   node版本：v8.2.1
                   npm版本:5.3.0

在虚拟机ubuntu 14.05上也报同样错误，node版本 v0.12.14，npm版本v2.15.1

具体错误如下：
`Uncaught TypeError: angular.module(...).info is not a function
    at vendor_app.js:19379
    at Object.102 (vendor_app.js:19792)
    at s (vendor_app.js:1)
    at vendor_app.js:1
    at Object.103../angular-resource (vendor_app.js:19795)
    at s (vendor_app.js:1)
    at vendor_app.js:1
    at Object.7.../bower_components/angular-chart.js/dist/angular-chart.js (vendor_app.js:10526)
    at s (vendor_app.js:1)
    at vendor_app.js:1
vendor_app.js:28245 Uncaught Error: [$injector:modulerr] Failed to instantiate module ebookcoinApp due to:
Error: [$injector:nomod] Module 'ebookcoinApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.32/$injector/nomod?p0=ebookcoinApp
    at http://localhost:7000/static/js/vendor_app.js:24416:12
    at http://localhost:7000/static/js/vendor_app.js:26017:17
    at ensure (http://localhost:7000/static/js/vendor_app.js:25941:38)
    at module (http://localhost:7000/static/js/vendor_app.js:26015:14)
    at http://localhost:7000/static/js/vendor_app.js:28217:22
    at forEach (http://localhost:7000/static/js/vendor_app.js:24663:18)
    at loadModules (http://localhost:7000/static/js/vendor_app.js:28211:5)
    at createInjector (http://localhost:7000/static/js/vendor_app.js:28151:11)
    at doBootstrap (http://localhost:7000/static/js/vendor_app.js:25784:20)
    at bootstrap (http://localhost:7000/static/js/vendor_app.js:25799:12)
http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=ebookcoinApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ebookcoinApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.32%2F%24injector%2Fnomod%3Fp0%3DebookcoinApp%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A24416%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A26017%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25941%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A26015%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28217%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A24663%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28211%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28151%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25784%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25799%3A12)
    at http://localhost:7000/static/js/vendor_app.js:24416:12
    at http://localhost:7000/static/js/vendor_app.js:26017:17
    at ensure (http://localhost:7000/static/js/vendor_app.js:25941:38)
    at module (http://localhost:7000/static/js/vendor_app.js:26015:14)
    at http://localhost:7000/static/js/vendor_app.js:28217:22
    at forEach (http://localhost:7000/static/js/vendor_app.js:24663:18)
    at loadModules (http://localhost:7000/static/js/vendor_app.js:28211:5)
    at createInjector (http://localhost:7000/static/js/vendor_app.js:28151:11)
    at doBootstrap (http://localhost:7000/static/js/vendor_app.js:25784:20)
    at bootstrap (http://localhost:7000/static/js/vendor_app.js:25799:12)
http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=ebookcoinApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ebookcoinApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.32%2F%24injector%2Fnomod%3Fp0%3DebookcoinApp%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A24416%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A26017%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25941%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A26015%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28217%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A24663%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28211%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A28151%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25784%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A7000%2Fstatic%2Fjs%2Fvendor_app.js%3A25799%3A12)
    at http://localhost:7000/static/js/vendor_app.js:24416:12
    at http://localhost:7000/static/js/vendor_app.js:28245:15
    at forEach (http://localhost:7000/static/js/vendor_app.js:24663:18)
    at loadModules (http://localhost:7000/static/js/vendor_app.js:28211:5)
    at createInjector (http://localhost:7000/static/js/vendor_app.js:28151:11)
    at doBootstrap (http://localhost:7000/static/js/vendor_app.js:25784:20)
    at bootstrap (http://localhost:7000/static/js/vendor_app.js:25799:12)
    at angularInit (http://localhost:7000/static/js/vendor_app.js:25708:5)
    at HTMLDocument.<anonymous> (http://localhost:7000/static/js/vendor_app.js:46530:5)
    at fire (http://localhost:7000/static/js/vendor_app.js:3871:31)`

**Comment by imfly** [comment]
您好，截图显示，底层已经正常启动。错误在前端部分，请参考 #9 的解释。

**Comment by zcjlq** [comment]
我将vendor_app.js中19379行注释掉，可以正常访问了。
`angular.module('ngResource', ['ng']).`
 ` // info({ angularVersion: '1.6.6' }).`
 ` provider('$resource', function ResourceProvider() {`
