### ISSUE TITLE
npm intall 出错

### ISSUE THREAD

**Issue by rogerfanrui** [Ebookcoin/ebookcoin#11]
hi,您的工程让我学到了很多,但是在执行编译的时候遇到了困难,
### 环境
- linux  Linux MiWiFi-R3-srv 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
- nodejs  v8.4.0
- npm 5.3.0
### error
16990 warn ebookcoin@0.1.3 No license field.
16991 verbose stack Error: ed25519@0.0.4 install: `node-gyp rebuild`
16991 verbose stack Exit status 1
16991 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs/node-v8.4.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
16991 verbose stack     at emitTwo (events.js:125:13)
16991 verbose stack     at EventEmitter.emit (events.js:213:7)
16991 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs/node-v8.4.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
16991 verbose stack     at emitTwo (events.js:125:13)
16991 verbose stack     at ChildProcess.emit (events.js:213:7)
16991 verbose stack     at maybeClose (internal/child_process.js:927:16)
16991 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by rogerfanrui** [comment]
已解决, 是因为使用了centeros6.5 版本太低导致
