### ISSUE TITLE
源码中dblite的问题，求解答

### ISSUE THREAD

**Issue by caiyifeng** [Ebookcoin/ebookcoin#20]
嗨，我买了nodejs开发区块链的书籍，，现在正在学习，，遇到问题，恳请指点：
app.js 374行有段代码
		dbLite: function (cb) {
			var dbLite = require('./helpers/dbLite.js');
			dbLite.connect(config.db, cb);
		},
总是如下报错，能帮忙解答下吗，我是在window8上执行的代码
internal/child_process.js:392
      throw errnoException(err, 'kill');
      ^

Error: kill EINVAL
    at _errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:13)
    at setUpAndGo (E:\node_workspace\test-node\node_modules\dblite\build\dblite.node.js:162:19)
    at Socket.onerror (E:\node_workspace\test-node\node_modules\dblite\build\dblite.node.js:135:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at onwriteError (_stream_writable.js:402:12)
    at onwrite (_stream_writable.js:430:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:561:3)

**Comment by imfly** [comment]
你用的最新版本的dblite吗？存在兼容性问题，改会原来的版本吧。

**Comment by caiyifeng** [comment]
多谢，已经解决了
