### ISSUE TITLE
node.js 版本导致执行`node app.js`错误

### ISSUE THREAD

**Issue by ArronYR** [Ebookcoin/ebookcoin#8]
### 系统
Mac 10.12.5
Windows 10

### 报错信息
```
log 2017-06-12 16:25:27 Ebookcoin started: 0.0.0.0:7000
fatal 2017-06-12 16:25:27 Domain master { message: 'Module version mismatch. Expected 48, got 47.',
stack: 'Error: Module version mismatch. Expected 48, got 47.\n    at Error (native)\n
at Object.Module._extensions..node (module.js:597:18)\n    
at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    
at Function.Module._load (module.js:438:3)\n   
at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    
at bindings (/node_workspace/ebookcoin/node_modules/bindings/bindings.js:76:44)\n    
at Object.<anonymous> (/node_workspace/ebookcoin/node_modules/ed25519/index.js:1:99)\n    
at Module._compile (module.js:570:32)' }
```

### node版本
|   正常   |     错误    |
|:-------:|:--------:|
| v5.10.0 | v6.8.0 |
| v5.2.0 | v0.12.9 |
| v8.1.1 |  v8.0.0 |
| v6.11.0 ||

**Comment by imfly** [comment]
:+1:

**Comment by HamiltonWang** [comment]
@imfly, 這個github 可以多找幾個人來幫你host 嗎？你這項目挺重要的耶，contributor 的人數多一點也是個重要的。
